typography_spectrum: 1
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.3848824647720903
  saturation: 0.34426446980796754
  rhythmicContrast: 0.9972079319413751
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.61687
analytics:
  google: null
  facebook: null
  twitter: null
name: ads
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
